CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL, updated_by VARCHAR(255) NOT NULL,
    is_delete BOOLEAN NOT NULL DEFAULT FALSE,
    room_number INTEGER NOT NULL UNIQUE CHECK (room_number BETWEEN 1 AND 100),
    floor VARCHAR(16) NOT NULL, room_type VARCHAR(50) NOT NULL, capacity INTEGER NOT NULL CHECK (capacity > 0),
    automatic_status VARCHAR(16) NOT NULL, manual_status VARCHAR(16)
);
