CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL, updated_by VARCHAR(255) NOT NULL,
    is_delete BOOLEAN NOT NULL DEFAULT FALSE,
    reservation_number VARCHAR(32) NOT NULL UNIQUE,
    guest_name VARCHAR(200) NOT NULL,
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL,
    user_id BIGINT REFERENCES app_users(id),
    CONSTRAINT reservation_dates_valid CHECK (check_out_date > check_in_date)
);
