CREATE TABLE reservation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL, updated_by VARCHAR(255) NOT NULL,
    is_delete BOOLEAN NOT NULL DEFAULT FALSE,
    type VARCHAR(20) NOT NULL, reservation_id BIGINT NOT NULL REFERENCES reservations(id),
    request_date TIMESTAMP NOT NULL, status VARCHAR(16) NOT NULL, notes VARCHAR(1000)
);
