CREATE TABLE corporate_affiliation_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL, created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL, updated_by VARCHAR(255) NOT NULL,
    is_delete BOOLEAN NOT NULL DEFAULT FALSE,
    ldap_username VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, generated_code VARCHAR(4) NOT NULL,
    expires_at TIMESTAMP NOT NULL, verified BOOLEAN NOT NULL DEFAULT FALSE, requested_at TIMESTAMP NOT NULL,
    verification_token VARCHAR(36)
);
